### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by allenck** [G6EJD/ESp32-e-paper-QRcode-generator#1]
I could not get this sketch to compile. I am using the Arduino IDE on linux so I believe the problem is that Linus is case sensitive. in epdif.cpp 
`#include <spi.h`
should be 
`#include <SPI.h>

and in epdif.h
`#include <arduino.h>` 
should be 
`#include <Arduino.h>`

**Comment by G6EJD** [comment]
You’ll need to inform the author of epdif.h of the errors. There is nothing I can do to solve that problem. You of course edit the epdif.h file and change the erroneous lines as you describe.
